package ed.wgu.zamzow.software_ii.controllers;

import ed.wgu.zamzow.software_ii.utils.Logging;
import javafx.scene.control.TextArea;

/**
 * Controller to view the logs generated by the login form
 *
 * @author Bret Zamzow
 */

public class LogViewController {


    public TextArea txtLogs;

    /**
     * Method to initialize the form and setup the main parts
     */
    public void initialize() {
        txtLogs.setText(Logging.ReadLog());
    }

}